<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Create User' => 'Новый пользователь',
	'Manage Users' => 'Управление пользователями',
	'Add User' => 'Добавить пользователя',
	'Save' => 'Сохранить',
	'Update Data' => 'Обновить данные',
	'Updating User Data' => 'Обновление данных пользователя',
	'Delete User' => 'Удалить пользователя',
	'Reset password' => 'Сброс пароля',
	'Reset' => 'Сбросить',
	'Search' => 'Поиск',
	'Advanced Search' => 'Расширеный поиск',
);
